spring:
  application:
    name: ssmtest01
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: root
  mybatis:
      mapper-locations: zy.mapper/**
      type-aliases-package: zy.entity/**
server:
  port: 8081